"""Create a baseline migrations

Revision ID: 4472c5ea86d5
Revises: 336d7a695e28
Create Date: 2024-08-12 22:26:39.031273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4472c5ea86d5'
down_revision: Union[str, None] = '336d7a695e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
