"""added work now for account

Revision ID: e3923a5c7a94
Revises: d2d43c2bd29e
Create Date: 2024-08-13 00:00:27.194006

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3923a5c7a94'
down_revision: Union[str, None] = 'd2d43c2bd29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_id', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'accounts',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column('last_game', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='accounts_pkey'),
    )
    op.create_index('ix_accounts_id', 'accounts', ['id'], unique=False)
    # ### end Alembic commands ###
